((magit-branch nil)
 (magit-cherry-pick
  ("--ff"))
 (magit-commit nil)
 (magit-diff
  ("--no-ext-diff" "--stat")
  ("--no-ext-diff")
  ("-U2" "--no-ext-diff")
  ("--ignore-space-change" "--ignore-all-space" "--no-ext-diff")
  ("--ignore-space-change" "--ignore-all-space" "--no-ext-diff" "--stat"))
 (magit-dispatch nil)
 (magit-fetch nil)
 (magit-log
  ("-n256" "--graph" "--decorate"))
 (magit-merge nil)
 (magit-pull nil)
 (magit-push nil)
 (magit-rebase nil)
 (magit-submodule nil)
 (magit-tag nil))
