;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        helm-confirm-and-exit-minibuffer
        text-scale-decrease
        ))

(setq mc/cmds-to-run-once
      '(
        crux-move-beginning-of-line
        crux-top-join-line
        describe-key
        easy-kill
        fill-paragraph
        helm-M-x
        helm-bookmarks
        helm-swoop
        indent-for-tab-command
        magit-status
        mark-whole-buffer
        mouse-buffer-menu
        mouse-save-then-kill
        mouse-set-region
        text-scale-increase
        ))
